### ISSUE TITLE
suggest migrating this repo to the GACS 'organization'

### ISSUE THREAD

**Issue by brandonnodnarb** [agrisemantics/2016_11_goettingen#2]

**Comment by tombaker** [comment]
Yes, absolutely - no longer any need to have a separate repo. I may have given Jennifer a link to materials there; I can't think of anyone else who would likely go looking in that repo.

**Comment by brandonnodnarb** [comment]
I think if the ownership is changed to the GACS org the entire repo will show up there *and* github handles the re-directs.  I'll investigate further, but, from memory, this is the case.

**Comment by brandonnodnarb** [comment]
Moved to archive
